server:
  port: 9090
  
  
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka   
  
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: service1
        uri: lb://SERVICE1/
        predicates:
        - Path=/service1/*
        
      - id: service2
        uri: lb://SERVICE2/
        predicates:
        - Path=/service2/*
        
      - id: service3
        uri: lb://SERVICE3/
        predicates:
        - Path=/service3/* 
   
                    
